---
name: Aggregate Post Summary Schedule
on:
  workflow_dispatch:
  schedule:
    - cron: "5 9 * * *"
jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup poetry
        run: pipx install poetry
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry
      - name: install libraries
        run: poetry install
      - name: run aggregate
        run: |
          poetry run bsky-counter \
            -u "${{ vars.bsky_handle }}" \
            -t "${{ vars.timezone }}" \
            ${{ vars.post_flag }} ${{ vars.logging_flag }} \
            -p "${{ vars.pixela_user }}" \
            -g "${{ vars.pixela_graph_id }}"
        env:
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          PIXELA_API_TOKEN: ${{ secrets.PIXELA_API_TOKEN }}